//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountTotalEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountTotalEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AcceptedRecords"/>
 *         &lt;element ref="{}RejectedRecords"/>
 *         &lt;element ref="{}TotalsRecords" minOccurs="0"/>
 *         &lt;element ref="{}UserTrailerTotals" minOccurs="0"/>
 *         &lt;element ref="{}AdjustmentRecords" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountTotalEntryType", propOrder = {
    "acceptedRecords",
    "rejectedRecords",
    "totalsRecords",
    "userTrailerTotals",
    "adjustmentRecords"
})
public class AccountTotalEntryType {

    @XmlElement(name = "AcceptedRecords", required = true)
    protected AmountSummaryType acceptedRecords;
    @XmlElement(name = "RejectedRecords", required = true)
    protected AmountSummaryType rejectedRecords;
    @XmlElement(name = "TotalsRecords")
    protected AmountSummaryType totalsRecords;
    @XmlElement(name = "UserTrailerTotals")
    protected AmountSummaryType userTrailerTotals;
    @XmlElement(name = "AdjustmentRecords")
    protected AmountSummaryType adjustmentRecords;

    /**
     * Gets the value of the acceptedRecords property.
     * 
     * @return
     *     possible object is
     *     {@link AmountSummaryType }
     *     
     */
    public AmountSummaryType getAcceptedRecords() {
        return acceptedRecords;
    }

    /**
     * Sets the value of the acceptedRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountSummaryType }
     *     
     */
    public void setAcceptedRecords(AmountSummaryType value) {
        this.acceptedRecords = value;
    }

    /**
     * Gets the value of the rejectedRecords property.
     * 
     * @return
     *     possible object is
     *     {@link AmountSummaryType }
     *     
     */
    public AmountSummaryType getRejectedRecords() {
        return rejectedRecords;
    }

    /**
     * Sets the value of the rejectedRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountSummaryType }
     *     
     */
    public void setRejectedRecords(AmountSummaryType value) {
        this.rejectedRecords = value;
    }

    /**
     * Gets the value of the totalsRecords property.
     * 
     * @return
     *     possible object is
     *     {@link AmountSummaryType }
     *     
     */
    public AmountSummaryType getTotalsRecords() {
        return totalsRecords;
    }

    /**
     * Sets the value of the totalsRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountSummaryType }
     *     
     */
    public void setTotalsRecords(AmountSummaryType value) {
        this.totalsRecords = value;
    }

    /**
     * Gets the value of the userTrailerTotals property.
     * 
     * @return
     *     possible object is
     *     {@link AmountSummaryType }
     *     
     */
    public AmountSummaryType getUserTrailerTotals() {
        return userTrailerTotals;
    }

    /**
     * Sets the value of the userTrailerTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountSummaryType }
     *     
     */
    public void setUserTrailerTotals(AmountSummaryType value) {
        this.userTrailerTotals = value;
    }

    /**
     * Gets the value of the adjustmentRecords property.
     * 
     * @return
     *     possible object is
     *     {@link AmountSummaryType }
     *     
     */
    public AmountSummaryType getAdjustmentRecords() {
        return adjustmentRecords;
    }

    /**
     * Sets the value of the adjustmentRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountSummaryType }
     *     
     */
    public void setAdjustmentRecords(AmountSummaryType value) {
        this.adjustmentRecords = value;
    }

}
