//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CreditEntry" minOccurs="0"/>
 *         &lt;element ref="{}DebitEntry" minOccurs="0"/>
 *         &lt;element ref="{}CreditContraEntry" minOccurs="0"/>
 *         &lt;element ref="{}DebitContraEntry" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sortCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creditEntry",
    "debitEntry",
    "creditContraEntry",
    "debitContraEntry"
})
@XmlRootElement(name = "AccountTotal")
public class AccountTotal {

    @XmlElement(name = "CreditEntry")
    protected AccountTotalEntryType creditEntry;
    @XmlElement(name = "DebitEntry")
    protected AccountTotalEntryType debitEntry;
    @XmlElement(name = "CreditContraEntry")
    protected AccountTotalEntryType creditContraEntry;
    @XmlElement(name = "DebitContraEntry")
    protected AccountTotalEntryType debitContraEntry;
    @XmlAttribute(name = "number", required = true)
    protected String number;
    @XmlAttribute(name = "sortCode")
    protected String sortCode;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the creditEntry property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public AccountTotalEntryType getCreditEntry() {
        return creditEntry;
    }

    /**
     * Sets the value of the creditEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public void setCreditEntry(AccountTotalEntryType value) {
        this.creditEntry = value;
    }

    /**
     * Gets the value of the debitEntry property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public AccountTotalEntryType getDebitEntry() {
        return debitEntry;
    }

    /**
     * Sets the value of the debitEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public void setDebitEntry(AccountTotalEntryType value) {
        this.debitEntry = value;
    }

    /**
     * Gets the value of the creditContraEntry property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public AccountTotalEntryType getCreditContraEntry() {
        return creditContraEntry;
    }

    /**
     * Sets the value of the creditContraEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public void setCreditContraEntry(AccountTotalEntryType value) {
        this.creditContraEntry = value;
    }

    /**
     * Gets the value of the debitContraEntry property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public AccountTotalEntryType getDebitContraEntry() {
        return debitContraEntry;
    }

    /**
     * Sets the value of the debitContraEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public void setDebitContraEntry(AccountTotalEntryType value) {
        this.debitContraEntry = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the sortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortCode() {
        return sortCode;
    }

    /**
     * Sets the value of the sortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortCode(String value) {
        this.sortCode = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
