//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CreditEntry"/>
 *         &lt;element ref="{}DebitEntry"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "creditEntry",
    "debitEntry"
})
@XmlRootElement(name = "AgreementOfFileTotals")
public class AgreementOfFileTotals {

    @XmlElement(name = "CreditEntry", required = true)
    protected AccountTotalEntryType creditEntry;
    @XmlElement(name = "DebitEntry", required = true)
    protected AccountTotalEntryType debitEntry;

    /**
     * Gets the value of the creditEntry property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public AccountTotalEntryType getCreditEntry() {
        return creditEntry;
    }

    /**
     * Sets the value of the creditEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public void setCreditEntry(AccountTotalEntryType value) {
        this.creditEntry = value;
    }

    /**
     * Gets the value of the debitEntry property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public AccountTotalEntryType getDebitEntry() {
        return debitEntry;
    }

    /**
     * Sets the value of the debitEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotalEntryType }
     *     
     */
    public void setDebitEntry(AccountTotalEntryType value) {
        this.debitEntry = value;
    }

}
