//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}UserFileInformation"/>
 *         &lt;element ref="{}DaySection"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ArrivalUserFile")
public class ArrivalUserFile {

    @XmlElement(name = "UserFileInformation", required = true)
    protected UserFileInformation userFileInformation;
    @XmlElement(name = "DaySection", required = true)
    protected DaySection daySection;

    /**
     * Gets the value of the userFileInformation property.
     * 
     * @return
     *     possible object is
     *     {@link UserFileInformation }
     *     
     */
    public UserFileInformation getUserFileInformation() {
        return userFileInformation;
    }

    /**
     * Sets the value of the userFileInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFileInformation }
     *     
     */
    public void setUserFileInformation(UserFileInformation value) {
        this.userFileInformation = value;
    }

    /**
     * Gets the value of the daySection property.
     * 
     * @return
     *     possible object is
     *     {@link DaySection }
     *     
     */
    public DaySection getDaySection() {
        return daySection;
    }

    /**
     * Sets the value of the daySection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaySection }
     *     
     */
    public void setDaySection(DaySection value) {
        this.daySection = value;
    }

}
