//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DaySectionRecord" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Totals" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="daySectionLevelErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "daySectionRecord",
    "totals"
})
@XmlRootElement(name = "DaySection")
public class DaySection {

    @XmlElement(name = "DaySectionRecord")
    protected List<DaySectionRecord> daySectionRecord;
    @XmlElement(name = "Totals")
    protected Totals totals;
    @XmlAttribute(name = "daySectionLevelErrorMessage")
    protected String daySectionLevelErrorMessage;

    /**
     * Gets the value of the daySectionRecord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the daySectionRecord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDaySectionRecord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DaySectionRecord }
     * 
     * 
     */
    public List<DaySectionRecord> getDaySectionRecord() {
        if (daySectionRecord == null) {
            daySectionRecord = new ArrayList<DaySectionRecord>();
        }
        return this.daySectionRecord;
    }

    /**
     * Gets the value of the totals property.
     * 
     * @return
     *     possible object is
     *     {@link Totals }
     *     
     */
    public Totals getTotals() {
        return totals;
    }

    /**
     * Sets the value of the totals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Totals }
     *     
     */
    public void setTotals(Totals value) {
        this.totals = value;
    }

    /**
     * Gets the value of the daySectionLevelErrorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaySectionLevelErrorMessage() {
        return daySectionLevelErrorMessage;
    }

    /**
     * Sets the value of the daySectionLevelErrorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaySectionLevelErrorMessage(String value) {
        this.daySectionLevelErrorMessage = value;
    }

}
