//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ProducedOn"/>
 *         &lt;element ref="{}ProcessingDate"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reportType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reportNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="batchNumber" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="reportSequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "producedOn",
    "processingDate"
})
@XmlRootElement(name = "Header")
public class Header {

    @XmlElement(name = "ProducedOn", required = true)
    protected ProducedOn producedOn;
    @XmlElement(name = "ProcessingDate", required = true)
    protected ProcessingDate processingDate;
    @XmlAttribute(name = "reportType", required = true)
    protected String reportType;
    @XmlAttribute(name = "reportNumber", required = true)
    protected BigInteger reportNumber;
    @XmlAttribute(name = "batchNumber")
    protected BigInteger batchNumber;
    @XmlAttribute(name = "reportSequenceNumber")
    protected String reportSequenceNumber;
    @XmlAttribute(name = "userNumber")
    protected String userNumber;

    /**
     * Gets the value of the producedOn property.
     * 
     * @return
     *     possible object is
     *     {@link ProducedOn }
     *     
     */
    public ProducedOn getProducedOn() {
        return producedOn;
    }

    /**
     * Sets the value of the producedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducedOn }
     *     
     */
    public void setProducedOn(ProducedOn value) {
        this.producedOn = value;
    }

    /**
     * Gets the value of the processingDate property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingDate }
     *     
     */
    public ProcessingDate getProcessingDate() {
        return processingDate;
    }

    /**
     * Sets the value of the processingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingDate }
     *     
     */
    public void setProcessingDate(ProcessingDate value) {
        this.processingDate = value;
    }

    /**
     * Gets the value of the reportType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * Sets the value of the reportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportType(String value) {
        this.reportType = value;
    }

    /**
     * Gets the value of the reportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReportNumber() {
        return reportNumber;
    }

    /**
     * Sets the value of the reportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReportNumber(BigInteger value) {
        this.reportNumber = value;
    }

    /**
     * Gets the value of the batchNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBatchNumber() {
        return batchNumber;
    }

    /**
     * Sets the value of the batchNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBatchNumber(BigInteger value) {
        this.batchNumber = value;
    }

    /**
     * Gets the value of the reportSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSequenceNumber() {
        return reportSequenceNumber;
    }

    /**
     * Sets the value of the reportSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSequenceNumber(String value) {
        this.reportSequenceNumber = value;
    }

    /**
     * Gets the value of the userNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * Sets the value of the userNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserNumber(String value) {
        this.userNumber = value;
    }

}
