//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AccountTotals" minOccurs="0"/>
 *         &lt;element ref="{}Adjustments" minOccurs="0"/>
 *         &lt;element ref="{}AgreementOfFileTotals"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountTotals",
    "adjustments",
    "agreementOfFileTotals"
})
@XmlRootElement(name = "InputReportSummary")
public class InputReportSummary {

    @XmlElement(name = "AccountTotals")
    protected AccountTotals accountTotals;
    @XmlElement(name = "Adjustments")
    protected Adjustments adjustments;
    @XmlElement(name = "AgreementOfFileTotals", required = true)
    protected AgreementOfFileTotals agreementOfFileTotals;

    /**
     * Gets the value of the accountTotals property.
     * 
     * @return
     *     possible object is
     *     {@link AccountTotals }
     *     
     */
    public AccountTotals getAccountTotals() {
        return accountTotals;
    }

    /**
     * Sets the value of the accountTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountTotals }
     *     
     */
    public void setAccountTotals(AccountTotals value) {
        this.accountTotals = value;
    }

    /**
     * Gets the value of the adjustments property.
     * 
     * @return
     *     possible object is
     *     {@link Adjustments }
     *     
     */
    public Adjustments getAdjustments() {
        return adjustments;
    }

    /**
     * Sets the value of the adjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adjustments }
     *     
     */
    public void setAdjustments(Adjustments value) {
        this.adjustments = value;
    }

    /**
     * Gets the value of the agreementOfFileTotals property.
     * 
     * @return
     *     possible object is
     *     {@link AgreementOfFileTotals }
     *     
     */
    public AgreementOfFileTotals getAgreementOfFileTotals() {
        return agreementOfFileTotals;
    }

    /**
     * Sets the value of the agreementOfFileTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgreementOfFileTotals }
     *     
     */
    public void setAgreementOfFileTotals(AgreementOfFileTotals value) {
        this.agreementOfFileTotals = value;
    }

}
