//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ail.eft.bacs.output.reports package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageLine_QNAME = new QName("", "MessageLine");
    private final static QName _OriginatingAccount_QNAME = new QName("", "OriginatingAccount");
    private final static QName _AdjustmentRecords_QNAME = new QName("", "AdjustmentRecords");
    private final static QName _Address3_QNAME = new QName("", "address3");
    private final static QName _Address2_QNAME = new QName("", "address2");
    private final static QName _DebitContraEntry_QNAME = new QName("", "DebitContraEntry");
    private final static QName _Address1_QNAME = new QName("", "address1");
    private final static QName _RejectedRecords_QNAME = new QName("", "RejectedRecords");
    private final static QName _TotalsRecords_QNAME = new QName("", "TotalsRecords");
    private final static QName _CreditContraEntry_QNAME = new QName("", "CreditContraEntry");
    private final static QName _DebitEntry_QNAME = new QName("", "DebitEntry");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _DestinationAccount_QNAME = new QName("", "DestinationAccount");
    private final static QName _Address5_QNAME = new QName("", "address5");
    private final static QName _Address4_QNAME = new QName("", "address4");
    private final static QName _CreditEntry_QNAME = new QName("", "CreditEntry");
    private final static QName _AcceptedRecords_QNAME = new QName("", "AcceptedRecords");
    private final static QName _UserTrailerTotals_QNAME = new QName("", "UserTrailerTotals");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ail.eft.bacs.output.reports
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BACSDocument }
     * 
     */
    public BACSDocument createBACSDocument() {
        return new BACSDocument();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link AccountTotalEntryType }
     * 
     */
    public AccountTotalEntryType createAccountTotalEntryType() {
        return new AccountTotalEntryType();
    }

    /**
     * Create an instance of {@link Adjustments }
     * 
     */
    public Adjustments createAdjustments() {
        return new Adjustments();
    }

    /**
     * Create an instance of {@link Adjustment }
     * 
     */
    public Adjustment createAdjustment() {
        return new Adjustment();
    }

    /**
     * Create an instance of {@link ErrorItem }
     * 
     */
    public ErrorItem createErrorItem() {
        return new ErrorItem();
    }

    /**
     * Create an instance of {@link AccountTotal }
     * 
     */
    public AccountTotal createAccountTotal() {
        return new AccountTotal();
    }

    /**
     * Create an instance of {@link UserFileInformation }
     * 
     */
    public UserFileInformation createUserFileInformation() {
        return new UserFileInformation();
    }

    /**
     * Create an instance of {@link AddresseeInformation }
     * 
     */
    public AddresseeInformation createAddresseeInformation() {
        return new AddresseeInformation();
    }

    /**
     * Create an instance of {@link AmountSummaryType }
     * 
     */
    public AmountSummaryType createAmountSummaryType() {
        return new AmountSummaryType();
    }

    /**
     * Create an instance of {@link Debit }
     * 
     */
    public Debit createDebit() {
        return new Debit();
    }

    /**
     * Create an instance of {@link Contra }
     * 
     */
    public Contra createContra() {
        return new Contra();
    }

    /**
     * Create an instance of {@link SubmissionInformation }
     * 
     */
    public SubmissionInformation createSubmissionInformation() {
        return new SubmissionInformation();
    }

    /**
     * Create an instance of {@link WithdrawalReport }
     * 
     */
    public WithdrawalReport createWithdrawalReport() {
        return new WithdrawalReport();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link ProducedOn }
     * 
     */
    public ProducedOn createProducedOn() {
        return new ProducedOn();
    }

    /**
     * Create an instance of {@link ProcessingDate }
     * 
     */
    public ProcessingDate createProcessingDate() {
        return new ProcessingDate();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Submission }
     * 
     */
    public Submission createSubmission() {
        return new Submission();
    }

    /**
     * Create an instance of {@link UserFile }
     * 
     */
    public UserFile createUserFile() {
        return new UserFile();
    }

    /**
     * Create an instance of {@link InputUserFile }
     * 
     */
    public InputUserFile createInputUserFile() {
        return new InputUserFile();
    }

    /**
     * Create an instance of {@link DaySection }
     * 
     */
    public DaySection createDaySection() {
        return new DaySection();
    }

    /**
     * Create an instance of {@link DaySectionRecord }
     * 
     */
    public DaySectionRecord createDaySectionRecord() {
        return new DaySectionRecord();
    }

    /**
     * Create an instance of {@link Credit }
     * 
     */
    public Credit createCredit() {
        return new Credit();
    }

    /**
     * Create an instance of {@link Totals }
     * 
     */
    public Totals createTotals() {
        return new Totals();
    }

    /**
     * Create an instance of {@link Errors }
     * 
     */
    public Errors createErrors() {
        return new Errors();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link TotalNumberOfErrors }
     * 
     */
    public TotalNumberOfErrors createTotalNumberOfErrors() {
        return new TotalNumberOfErrors();
    }

    /**
     * Create an instance of {@link InputReportSummary }
     * 
     */
    public InputReportSummary createInputReportSummary() {
        return new InputReportSummary();
    }

    /**
     * Create an instance of {@link AccountTotals }
     * 
     */
    public AccountTotals createAccountTotals() {
        return new AccountTotals();
    }

    /**
     * Create an instance of {@link AgreementOfFileTotals }
     * 
     */
    public AgreementOfFileTotals createAgreementOfFileTotals() {
        return new AgreementOfFileTotals();
    }

    /**
     * Create an instance of {@link WithdrawalUserFile }
     * 
     */
    public WithdrawalUserFile createWithdrawalUserFile() {
        return new WithdrawalUserFile();
    }

    /**
     * Create an instance of {@link ArrivalUserFile }
     * 
     */
    public ArrivalUserFile createArrivalUserFile() {
        return new ArrivalUserFile();
    }

    /**
     * Create an instance of {@link BACSDocument.Data }
     * 
     */
    public BACSDocument.Data createBACSDocumentData() {
        return new BACSDocument.Data();
    }

    /**
     * Create an instance of {@link InputReport }
     * 
     */
    public InputReport createInputReport() {
        return new InputReport();
    }

    /**
     * Create an instance of {@link ArrivalReport }
     * 
     */
    public ArrivalReport createArrivalReport() {
        return new ArrivalReport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MessageLine")
    public JAXBElement<String> createMessageLine(String value) {
        return new JAXBElement<String>(_MessageLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OriginatingAccount")
    public JAXBElement<AccountType> createOriginatingAccount(AccountType value) {
        return new JAXBElement<AccountType>(_OriginatingAccount_QNAME, AccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountSummaryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AdjustmentRecords")
    public JAXBElement<AmountSummaryType> createAdjustmentRecords(AmountSummaryType value) {
        return new JAXBElement<AmountSummaryType>(_AdjustmentRecords_QNAME, AmountSummaryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address3")
    public JAXBElement<String> createAddress3(String value) {
        return new JAXBElement<String>(_Address3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTotalEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DebitContraEntry")
    public JAXBElement<AccountTotalEntryType> createDebitContraEntry(AccountTotalEntryType value) {
        return new JAXBElement<AccountTotalEntryType>(_DebitContraEntry_QNAME, AccountTotalEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address1")
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountSummaryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RejectedRecords")
    public JAXBElement<AmountSummaryType> createRejectedRecords(AmountSummaryType value) {
        return new JAXBElement<AmountSummaryType>(_RejectedRecords_QNAME, AmountSummaryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountSummaryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalsRecords")
    public JAXBElement<AmountSummaryType> createTotalsRecords(AmountSummaryType value) {
        return new JAXBElement<AmountSummaryType>(_TotalsRecords_QNAME, AmountSummaryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTotalEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditContraEntry")
    public JAXBElement<AccountTotalEntryType> createCreditContraEntry(AccountTotalEntryType value) {
        return new JAXBElement<AccountTotalEntryType>(_CreditContraEntry_QNAME, AccountTotalEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTotalEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DebitEntry")
    public JAXBElement<AccountTotalEntryType> createDebitEntry(AccountTotalEntryType value) {
        return new JAXBElement<AccountTotalEntryType>(_DebitEntry_QNAME, AccountTotalEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DestinationAccount")
    public JAXBElement<AccountType> createDestinationAccount(AccountType value) {
        return new JAXBElement<AccountType>(_DestinationAccount_QNAME, AccountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address5")
    public JAXBElement<String> createAddress5(String value) {
        return new JAXBElement<String>(_Address5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address4")
    public JAXBElement<String> createAddress4(String value) {
        return new JAXBElement<String>(_Address4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTotalEntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreditEntry")
    public JAXBElement<AccountTotalEntryType> createCreditEntry(AccountTotalEntryType value) {
        return new JAXBElement<AccountTotalEntryType>(_CreditEntry_QNAME, AccountTotalEntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountSummaryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AcceptedRecords")
    public JAXBElement<AmountSummaryType> createAcceptedRecords(AmountSummaryType value) {
        return new JAXBElement<AmountSummaryType>(_AcceptedRecords_QNAME, AmountSummaryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmountSummaryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserTrailerTotals")
    public JAXBElement<AmountSummaryType> createUserTrailerTotals(AmountSummaryType value) {
        return new JAXBElement<AmountSummaryType>(_UserTrailerTotals_QNAME, AmountSummaryType.class, null, value);
    }

}
