//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="submissionReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="media" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bureauName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="volumeSerialNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bureauSponsor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="bureauNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "SubmissionInformation")
public class SubmissionInformation {

    @XmlAttribute(name = "submissionReferenceNumber")
    protected String submissionReferenceNumber;
    @XmlAttribute(name = "media")
    protected String media;
    @XmlAttribute(name = "bureauName")
    protected String bureauName;
    @XmlAttribute(name = "volumeSerialNumber", required = true)
    protected String volumeSerialNumber;
    @XmlAttribute(name = "bureauSponsor")
    protected String bureauSponsor;
    @XmlAttribute(name = "bureauNumber")
    protected String bureauNumber;

    /**
     * Gets the value of the submissionReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmissionReferenceNumber() {
        return submissionReferenceNumber;
    }

    /**
     * Sets the value of the submissionReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionReferenceNumber(String value) {
        this.submissionReferenceNumber = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedia(String value) {
        this.media = value;
    }

    /**
     * Gets the value of the bureauName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauName() {
        return bureauName;
    }

    /**
     * Sets the value of the bureauName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauName(String value) {
        this.bureauName = value;
    }

    /**
     * Gets the value of the volumeSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeSerialNumber() {
        return volumeSerialNumber;
    }

    /**
     * Sets the value of the volumeSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeSerialNumber(String value) {
        this.volumeSerialNumber = value;
    }

    /**
     * Gets the value of the bureauSponsor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauSponsor() {
        return bureauSponsor;
    }

    /**
     * Sets the value of the bureauSponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauSponsor(String value) {
        this.bureauSponsor = value;
    }

    /**
     * Gets the value of the bureauNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauNumber() {
        return bureauNumber;
    }

    /**
     * Sets the value of the bureauNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauNumber(String value) {
        this.bureauNumber = value;
    }

}
