//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="amendedRecords" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="returnedRecords" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="rejectedRecords" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "TotalNumberOfErrors")
public class TotalNumberOfErrors {

    @XmlAttribute(name = "amendedRecords", required = true)
    protected BigInteger amendedRecords;
    @XmlAttribute(name = "returnedRecords", required = true)
    protected BigInteger returnedRecords;
    @XmlAttribute(name = "rejectedRecords", required = true)
    protected BigInteger rejectedRecords;

    /**
     * Gets the value of the amendedRecords property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAmendedRecords() {
        return amendedRecords;
    }

    /**
     * Sets the value of the amendedRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAmendedRecords(BigInteger value) {
        this.amendedRecords = value;
    }

    /**
     * Gets the value of the returnedRecords property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReturnedRecords() {
        return returnedRecords;
    }

    /**
     * Sets the value of the returnedRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReturnedRecords(BigInteger value) {
        this.returnedRecords = value;
    }

    /**
     * Gets the value of the rejectedRecords property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRejectedRecords() {
        return rejectedRecords;
    }

    /**
     * Sets the value of the rejectedRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRejectedRecords(BigInteger value) {
        this.rejectedRecords = value;
    }

}
