//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}InputUserFile"/>
 *         &lt;element ref="{}WithdrawalUserFile"/>
 *         &lt;element ref="{}ArrivalUserFile"/>
 *       &lt;/choice>
 *       &lt;attribute name="fileLevelMessage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputUserFile",
    "withdrawalUserFile",
    "arrivalUserFile"
})
@XmlRootElement(name = "UserFile")
public class UserFile {

    @XmlElement(name = "InputUserFile")
    protected InputUserFile inputUserFile;
    @XmlElement(name = "WithdrawalUserFile")
    protected WithdrawalUserFile withdrawalUserFile;
    @XmlElement(name = "ArrivalUserFile")
    protected ArrivalUserFile arrivalUserFile;
    @XmlAttribute(name = "fileLevelMessage")
    protected String fileLevelMessage;

    /**
     * Gets the value of the inputUserFile property.
     * 
     * @return
     *     possible object is
     *     {@link InputUserFile }
     *     
     */
    public InputUserFile getInputUserFile() {
        return inputUserFile;
    }

    /**
     * Sets the value of the inputUserFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputUserFile }
     *     
     */
    public void setInputUserFile(InputUserFile value) {
        this.inputUserFile = value;
    }

    /**
     * Gets the value of the withdrawalUserFile property.
     * 
     * @return
     *     possible object is
     *     {@link WithdrawalUserFile }
     *     
     */
    public WithdrawalUserFile getWithdrawalUserFile() {
        return withdrawalUserFile;
    }

    /**
     * Sets the value of the withdrawalUserFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link WithdrawalUserFile }
     *     
     */
    public void setWithdrawalUserFile(WithdrawalUserFile value) {
        this.withdrawalUserFile = value;
    }

    /**
     * Gets the value of the arrivalUserFile property.
     * 
     * @return
     *     possible object is
     *     {@link ArrivalUserFile }
     *     
     */
    public ArrivalUserFile getArrivalUserFile() {
        return arrivalUserFile;
    }

    /**
     * Sets the value of the arrivalUserFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrivalUserFile }
     *     
     */
    public void setArrivalUserFile(ArrivalUserFile value) {
        this.arrivalUserFile = value;
    }

    /**
     * Gets the value of the fileLevelMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLevelMessage() {
        return fileLevelMessage;
    }

    /**
     * Sets the value of the fileLevelMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLevelMessage(String value) {
        this.fileLevelMessage = value;
    }

}
