//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:35:45 AM GMT 
//


package com.ail.eft.bacs.output.reports;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="userNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userFileNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fileCurrency" use="required" type="{}CurrencyType" />
 *       &lt;attribute name="uhl1WorkCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uhl1ProcessingDate" type="{}UserInputDate" />
 *       &lt;attribute name="fileReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="userSponsor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "UserFileInformation")
public class UserFileInformation {

    @XmlAttribute(name = "userNumber", required = true)
    protected String userNumber;
    @XmlAttribute(name = "userName")
    protected String userName;
    @XmlAttribute(name = "userFileNumber", required = true)
    protected String userFileNumber;
    @XmlAttribute(name = "sequenceNumber")
    protected String sequenceNumber;
    @XmlAttribute(name = "fileCurrency", required = true)
    protected String fileCurrency;
    @XmlAttribute(name = "uhl1WorkCode", required = true)
    protected String uhl1WorkCode;
    @XmlAttribute(name = "uhl1ProcessingDate")
    protected String uhl1ProcessingDate;
    @XmlAttribute(name = "fileReferenceNumber")
    protected String fileReferenceNumber;
    @XmlAttribute(name = "userSponsor")
    protected String userSponsor;

    /**
     * Gets the value of the userNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * Sets the value of the userNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserNumber(String value) {
        this.userNumber = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the userFileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFileNumber() {
        return userFileNumber;
    }

    /**
     * Sets the value of the userFileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFileNumber(String value) {
        this.userFileNumber = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the fileCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileCurrency() {
        return fileCurrency;
    }

    /**
     * Sets the value of the fileCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileCurrency(String value) {
        this.fileCurrency = value;
    }

    /**
     * Gets the value of the uhl1WorkCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUhl1WorkCode() {
        return uhl1WorkCode;
    }

    /**
     * Sets the value of the uhl1WorkCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUhl1WorkCode(String value) {
        this.uhl1WorkCode = value;
    }

    /**
     * Gets the value of the uhl1ProcessingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUhl1ProcessingDate() {
        return uhl1ProcessingDate;
    }

    /**
     * Sets the value of the uhl1ProcessingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUhl1ProcessingDate(String value) {
        this.uhl1ProcessingDate = value;
    }

    /**
     * Gets the value of the fileReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileReferenceNumber() {
        return fileReferenceNumber;
    }

    /**
     * Sets the value of the fileReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileReferenceNumber(String value) {
        this.fileReferenceNumber = value;
    }

    /**
     * Gets the value of the userSponsor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserSponsor() {
        return userSponsor;
    }

    /**
     * Sets the value of the userSponsor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserSponsor(String value) {
        this.userSponsor = value;
    }

}
