insert into bodENBodyType (name, validFrom, validTo) values('HATCHBACK', null, null);
insert into bodENBodyType (name, validFrom, validTo) values('SALOON', null, null);
insert into bodENBodyType (name, validFrom, validTo) values('SPORTS', null, null);
insert into bodENBodyType (name, validFrom, validTo) values('COUPE', null, null);
insert into bodENBodyType (name, validFrom, validTo) values('4X4', null, null);
insert into bodENBodyType (name, validFrom, validTo) values('ESTATE', null, null);
insert into bodENBodyType (name, validFrom, validTo) values('CONVERTIBLE', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AED', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AFN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ALL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AMD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ANG', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AOA', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ARS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AUD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AWG', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('AZN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BAM', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BBD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BDT', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BGN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BHD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BIF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BMD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BND', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BOB', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BOV', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BRL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BSD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BTN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BWP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BYR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('BZD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CAD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CDF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CHE', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CHF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CHW', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CLF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CLP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CNY', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('COP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('COU', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CRC', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CUC', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CUP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CVE', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('CZK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('DJF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('DKK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('DOP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('DZD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('EGP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ERN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ETB', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('EUR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('FJD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('FKP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GBP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GEL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GHS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GIP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GMD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GNF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GTQ', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('GYD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('HKD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('HNL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('HRK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('HTG', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('HUF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('IDR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ILS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('INR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('IQD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('IRR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ISK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('JMD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('JOD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('JPY', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KES', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KGS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KHR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KMF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KPW', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KRW', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KWD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KYD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('KZT', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LAK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LBP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LKR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LRD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LSL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LTL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LVL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('LYD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MAD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MDL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MGA', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MKD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MMK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MNT', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MOP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MRO', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MUR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MVR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MWK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MXN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MXV', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MYR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('MZN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('NAD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('NGN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('NIO', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('NOK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('NPR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('NZD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('OMR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PAB', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PEN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PGK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PHP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PKR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PLN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('PYG', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('QAR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('RON', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('RSD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('RUB', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('RWF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SAR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SBD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SCR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SDG', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SEK', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SGD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SHP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SLL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SOS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SRD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SSP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('STD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SVC', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SYP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('SZL', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('THB', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TJS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TMT', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TND', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TOP', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TRY', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TTD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TWD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('TZS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('UAH', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('UGX', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('USD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('USN', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('USS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('UYI', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('UYU', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('UZS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('VEF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('VND', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('VUV', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('WST', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XAF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XAG', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XAU', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XBA', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XBB', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XBC', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XBD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XCD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XDR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XFU', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XOF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XPD', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XPF', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XPT', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XSU', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XTS', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XUA', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('XXX', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('YER', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ZAR', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ZMW', null, null);
insert into ccyENCurrency (name, validFrom, validTo) values('ZWL', null, null);
insert into claENClaimType (name, validFrom, validTo) values('MOTOR OWN DAMAGE', null, null);
insert into claENClaimType (name, validFrom, validTo) values('MOTOR FIRE AND THEFT', null, null);
insert into claENClaimType (name, validFrom, validTo) values('THIRD PARTY PROPERTY DAMAGE', null, null);
insert into claENClaimType (name, validFrom, validTo) values('THIRD PARTY INJURY', null, null);
insert into claENClaimType (name, validFrom, validTo) values('ECOWAS BROWN CARD', null, null);
insert into claENClaimType (name, validFrom, validTo) values('DAMAGE TO VEHICLE BY FIRE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AF', 'AFGHANISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AX', 'ALAND ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AL', 'ALBANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DZ', 'ALGERIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AS', 'AMERICAN SAMOA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AD', 'ANDORRA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AO', 'ANGOLA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AI', 'ANGUILLA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AQ', 'ANTARCTICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AG', 'ANTIGUA AND BARBUDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AR', 'ARGENTINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AM', 'ARMENIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AW', 'ARUBA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AU', 'AUSTRALIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AT', 'AUSTRIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AZ', 'AZERBAIJAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BS', 'BAHAMAS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BH', 'BAHRAIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BD', 'BANGLADESH', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BB', 'BARBADOS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BY', 'BELARUS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BE', 'BELGIUM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BZ', 'BELIZE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BJ', 'BENIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BM', 'BERMUDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BT', 'BHUTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BO', 'BOLIVIA, PLURINATIONAL STATE OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BQ', 'BONAIRE, SINT EUSTATIUS AND SABA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BA', 'BOSNIA AND HERZEGOVINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BW', 'BOTSWANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BV', 'BOUVET ISLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BR', 'BRAZIL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IO', 'BRITISH INDIAN OCEAN TERRITORY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BN', 'BRUNEI DARUSSALAM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BG', 'BULGARIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BF', 'BURKINA FASO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BI', 'BURUNDI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KH', 'CAMBODIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CM', 'CAMEROON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CA', 'CANADA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CV', 'CAPE VERDE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KY', 'CAYMAN ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CF', 'CENTRAL AFRICAN REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TD', 'CHAD', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CL', 'CHILE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CN', 'CHINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CX', 'CHRISTMAS ISLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CC', 'COCOS (KEELING) ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CO', 'COLOMBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KM', 'COMOROS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CG', 'CONGO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CK', 'COOK ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CR', 'COSTA RICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CI', 'COTE DIVOIRE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HR', 'CROATIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CU', 'CUBA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CW', 'CURACAO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CY', 'CYPRUS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CZ', 'CZECH REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DK', 'DENMARK', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DJ', 'DJIBOUTI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DM', 'DOMINICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DO', 'DOMINICAN REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EC', 'ECUADOR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EG', 'EGYPT', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SV', 'EL SALVADOR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GQ', 'EQUATORIAL GUINEA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ER', 'ERITREA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EE', 'ESTONIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ET', 'ETHIOPIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FK', 'FALKLAND ISLANDS (MALVINAS)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FO', 'FAROE ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FJ', 'FIJI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FI', 'FINLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FR', 'FRANCE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GF', 'FRENCH GUIANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PF', 'FRENCH POLYNESIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TF', 'FRENCH SOUTHERN TERRITORIES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GA', 'GABON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GM', 'GAMBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GE', 'GEORGIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('DE', 'GERMANY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GH', 'GHANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GI', 'GIBRALTAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GR', 'GREECE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GL', 'GREENLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GD', 'GRENADA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GP', 'GUADELOUPE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GU', 'GUAM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GT', 'GUATEMALA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GG', 'GUERNSEY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GN', 'GUINEA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GW', 'GUINEA-BISSAU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GY', 'GUYANA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HT', 'HAITI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VA', 'HOLY SEE (VATICAN CITY STATE)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HN', 'HONDURAS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HK', 'HONG KONG', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('HU', 'HUNGARY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IS', 'ICELAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IN', 'INDIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ID', 'INDONESIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IR', 'IRAN, ISLAMIC REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IQ', 'IRAQ', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IE', 'IRELAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IM', 'ISLE OF MAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IL', 'ISRAEL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('IT', 'ITALY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JM', 'JAMAICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JP', 'JAPAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JE', 'JERSEY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('JO', 'JORDAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KZ', 'KAZAKHSTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KE', 'KENYA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KI', 'KIRIBATI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KP', 'KOREA, DEMOCRATIC PEOPLES REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KR', 'KOREA, REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KW', 'KUWAIT', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KG', 'KYRGYZSTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LA', 'LAO PEOPLES DEMOCRATIC REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LV', 'LATVIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LB', 'LEBANON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LS', 'LESOTHO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LR', 'LIBERIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LY', 'LIBYA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LI', 'LIECHTENSTEIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LT', 'LITHUANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LU', 'LUXEMBOURG', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MO', 'MACAO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MG', 'MADAGASCAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MW', 'MALAWI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MY', 'MALAYSIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MV', 'MALDIVES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ML', 'MALI', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MT', 'MALTA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MH', 'MARSHALL ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MQ', 'MARTINIQUE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MR', 'MAURITANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MU', 'MAURITIUS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('YT', 'MAYOTTE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MX', 'MEXICO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('FM', 'MICRONESIA, FEDERATED STATES OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MD', 'MOLDOVA, REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MC', 'MONACO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MN', 'MONGOLIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ME', 'MONTENEGRO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MS', 'MONTSERRAT', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MA', 'MOROCCO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MZ', 'MOZAMBIQUE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MM', 'MYANMAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NA', 'NAMIBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NR', 'NAURU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NP', 'NEPAL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NL', 'NETHERLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NC', 'NEW CALEDONIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NZ', 'NEW ZEALAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NI', 'NICARAGUA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NE', 'NIGER', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NG', 'NIGERIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NU', 'NIUE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NF', 'NORFOLK ISLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MP', 'NORTHERN MARIANA ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('NO', 'NORWAY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('OM', 'OMAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PK', 'PAKISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PW', 'PALAU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PS', 'PALESTINE, STATE OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PA', 'PANAMA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PG', 'PAPUA NEW GUINEA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PY', 'PARAGUAY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PE', 'PERU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PH', 'PHILIPPINES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PN', 'PITCAIRN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PL', 'POLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PT', 'PORTUGAL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PR', 'PUERTO RICO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('QA', 'QATAR', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RE', 'REUNION', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RO', 'ROMANIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RU', 'RUSSIAN FEDERATION', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RW', 'RWANDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('BL', 'SAINT BARTHELEMY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SH', 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('KN', 'SAINT KITTS AND NEVIS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LC', 'SAINT LUCIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('MF', 'SAINT MARTIN (FRENCH PART)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('PM', 'SAINT PIERRE AND MIQUELON', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VC', 'SAINT VINCENT AND THE GRENADINES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('WS', 'SAMOA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SM', 'SAN MARINO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ST', 'SAO TOME AND PRINCIPE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SA', 'SAUDI ARABIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SN', 'SENEGAL', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('RS', 'SERBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SC', 'SEYCHELLES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SL', 'SIERRA LEONE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SG', 'SINGAPORE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SX', 'SINT MAARTEN (DUTCH PART)', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SK', 'SLOVAKIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SI', 'SLOVENIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SB', 'SOLOMON ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SO', 'SOMALIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ZA', 'SOUTH AFRICA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SS', 'SOUTH SUDAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ES', 'SPAIN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('LK', 'SRI LANKA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SD', 'SUDAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SR', 'SURINAME', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SJ', 'SVALBARD AND JAN MAYEN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SZ', 'SWAZILAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SE', 'SWEDEN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('CH', 'SWITZERLAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('SY', 'SYRIAN ARAB REPUBLIC', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TW', 'TAIWAN, PROVINCE OF CHINA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TJ', 'TAJIKISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TZ', 'TANZANIA, UNITED REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TH', 'THAILAND', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TL', 'TIMOR-LESTE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TG', 'TOGO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TK', 'TOKELAU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TO', 'TONGA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TT', 'TRINIDAD AND TOBAGO', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TN', 'TUNISIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TR', 'TURKEY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TM', 'TURKMENISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TC', 'TURKS AND CAICOS ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('TV', 'TUVALU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UG', 'UGANDA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UA', 'UKRAINE', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('AE', 'UNITED ARAB EMIRATES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('GB', 'UNITED KINGDOM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('US', 'UNITED STATES', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UY', 'URUGUAY', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('UZ', 'UZBEKISTAN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VU', 'VANUATU', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VE', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VN', 'VIET NAM', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VG', 'VIRGIN ISLANDS, BRITISH', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('VI', 'VIRGIN ISLANDS, U.S.', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('WF', 'WALLIS AND FUTUNA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('EH', 'WESTERN SAHARA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('YE', 'YEMEN', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ZM', 'ZAMBIA', null, null);
insert into couENCountry (name, country, validFrom, validTo) values('ZW', 'ZIMBABWE', null, null);
insert into covENCover (name, validFrom, validTo) values('THIRD PARTY ONLY', null, null);
insert into covENCover (name, validFrom, validTo) values('THIRD PARTY FIRE AND THEFT', null, null);
insert into covENCover (name, validFrom, validTo) values('COMPREHENSIVE', null, null);
insert into empENEmploymentType (name, validFrom, validTo) values('FULL-TIME', null, null);
insert into empENEmploymentType (name, validFrom, validTo) values('PART-TIME', null, null);
insert into empENEmploymentType (name, validFrom, validTo) values('UNEMPLOYED', null, null);
insert into insENInsuredType (name, validFrom, validTo) values('PERSONAL', null, null);
insert into insENInsuredType (name, validFrom, validTo) values('CORPORATE', null, null);
insert into natENNationality (name, validFrom, validTo) values('AFGHAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ALBANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ALGERIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AMERICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ANDORRAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ANGOLAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ANTIGUANS', null, null);
insert into natENNationality (name, validFrom, validTo) values('ARGENTINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ARMENIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AUSTRALIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AUSTRIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('AZERBAIJANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('BAHAMIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BAHRAINI', null, null);
insert into natENNationality (name, validFrom, validTo) values('BANGLADESHI', null, null);
insert into natENNationality (name, validFrom, validTo) values('BARBADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BARBUDANS', null, null);
insert into natENNationality (name, validFrom, validTo) values('BATSWANA', null, null);
insert into natENNationality (name, validFrom, validTo) values('BELARUSIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BELGIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BELIZEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BENINESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BHUTANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BOLIVIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BOSNIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BRAZILIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BRITISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('BRUNEIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BULGARIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('BURKINABE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BURMESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('BURUNDIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CAMBODIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CAMEROONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CANADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CAPE VERDEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CENTRAL AFRICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CHADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CHILEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CHINESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('COLOMBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('COMORAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CONGOLESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('COSTA RICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CROATIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CUBAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('CYPRIOT', null, null);
insert into natENNationality (name, validFrom, validTo) values('CZECH', null, null);
insert into natENNationality (name, validFrom, validTo) values('DANISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('DJIBOUTI', null, null);
insert into natENNationality (name, validFrom, validTo) values('DOMINICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('DUTCH', null, null);
insert into natENNationality (name, validFrom, validTo) values('EAST TIMORESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('ECUADOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('EGYPTIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('EMIRIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('EQUATORIAL GUINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ERITREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ESTONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ETHIOPIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('FIJIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('FILIPINO', null, null);
insert into natENNationality (name, validFrom, validTo) values('FINNISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('FRENCH', null, null);
insert into natENNationality (name, validFrom, validTo) values('GABONESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('GAMBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GEORGIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GERMAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GHANAIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GREEK', null, null);
insert into natENNationality (name, validFrom, validTo) values('GRENADIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUATEMALAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUINEA-BISSAUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('GUYANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('HAITIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('HERZEGOVINIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('HONDURAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('HUNGARIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ICELANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('INDIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('INDONESIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('IRANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('IRAQI', null, null);
insert into natENNationality (name, validFrom, validTo) values('IRISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('ISRAELI', null, null);
insert into natENNationality (name, validFrom, validTo) values('ITALIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('IVORIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('JAMAICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('JAPANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('JORDANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('KAZAKHSTANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('KENYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('KITTIAN AND NEVISIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('KUWAITI', null, null);
insert into natENNationality (name, validFrom, validTo) values('KYRGYZ', null, null);
insert into natENNationality (name, validFrom, validTo) values('LAOTIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LATVIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LEBANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('LIBERIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LIBYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LIECHTENSTEINER', null, null);
insert into natENNationality (name, validFrom, validTo) values('LITHUANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('LUXEMBOURGER', null, null);
insert into natENNationality (name, validFrom, validTo) values('MACEDONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALAGASY', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALAWIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALAYSIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALDIVAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MALTESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('MARSHALLESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('MAURITANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MAURITIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MEXICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MICRONESIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOLDOVAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MONACAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MONGOLIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOROCCAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOSOTHO', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOTSWANA', null, null);
insert into natENNationality (name, validFrom, validTo) values('MOZAMBICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NAMIBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NAURUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NEPALESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('NETHERLANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('NEW ZEALANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('NI-VANUATU', null, null);
insert into natENNationality (name, validFrom, validTo) values('NICARAGUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NIGERIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NIGERIEN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NORTH KOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('NORTHERN IRISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('NORWEGIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('OMANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('PAKISTANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('PALAUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PANAMANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PAPUA NEW GUINEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PARAGUAYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('PERUVIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('POLISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('PORTUGUESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('QATARI', null, null);
insert into natENNationality (name, validFrom, validTo) values('ROMANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('RUSSIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('RWANDAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAINT LUCIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SALVADORAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAMOAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAN MARINESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAO TOMEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SAUDI', null, null);
insert into natENNationality (name, validFrom, validTo) values('SCOTTISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('SENEGALESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('SERBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SEYCHELLOIS', null, null);
insert into natENNationality (name, validFrom, validTo) values('SIERRA LEONEAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SINGAPOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SLOVAKIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SLOVENIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOLOMON ISLANDER', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOMALI', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOUTH AFRICAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SOUTH KOREAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SPANISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('SRI LANKAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('SUDANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('SURINAMER', null, null);
insert into natENNationality (name, validFrom, validTo) values('SWAZI', null, null);
insert into natENNationality (name, validFrom, validTo) values('SWEDISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('SWISS', null, null);
insert into natENNationality (name, validFrom, validTo) values('SYRIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TAIWANESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('TAJIK', null, null);
insert into natENNationality (name, validFrom, validTo) values('TANZANIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('THAI', null, null);
insert into natENNationality (name, validFrom, validTo) values('TOGOLESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('TONGAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TRINIDADIAN OR TOBAGONIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TUNISIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('TURKISH', null, null);
insert into natENNationality (name, validFrom, validTo) values('TUVALUAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('UGANDAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('UKRAINIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('URUGUAYAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('UZBEKISTANI', null, null);
insert into natENNationality (name, validFrom, validTo) values('VENEZUELAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('VIETNAMESE', null, null);
insert into natENNationality (name, validFrom, validTo) values('WELSH', null, null);
insert into natENNationality (name, validFrom, validTo) values('YEMENITE', null, null);
insert into natENNationality (name, validFrom, validTo) values('ZAMBIAN', null, null);
insert into natENNationality (name, validFrom, validTo) values('ZIMBABWEAN', null, null);
insert into parENParked (name, validFrom, validTo) values('ON ROAD', null, null);
insert into parENParked (name, validFrom, validTo) values('OFF ROAD', null, null);
insert into parENParked (name, validFrom, validTo) values('GARAGE', null, null);
insert into reaENReason (name, validFrom, validTo) values('NEW BUSINESS', null, null);
insert into reaENReason (name, validFrom, validTo) values('ENDORSEMENT', null, null);
insert into reaENReason (name, validFrom, validTo) values('CANCELLATION', null, null);
insert into reaENReason (name, validFrom, validTo) values('CLAIM', null, null);
insert into reaENReason (name, validFrom, validTo) values('RENEWAL', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('X.1', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('X.4', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('TAXI-Z405', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('HIRING CARS-Z405', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('MINI BUS-Z405', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('MAXI BUS-Z405', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('AMBULANCE / HEARSE-Z405', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Z.301 BELOW 3000 CC', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Z.301 ABOVE 3000 CC', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('ART/TANKER Z301', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Z.300 BELOW 3000 CC', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Z.300 ABOVE 3000 CC', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Z.802 SITE', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Z.802 ROAD', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('GWI- CLASS I', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('CLASS II', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('CLASS III', null, null);
insert into risENRiskCode (name, validFrom, validTo) values('Y.3', null, null);insert into weiENWeightType (name, validFrom, validTo) values('LB', null, null);
insert into weiENWeightType (name, validFrom, validTo) values('KG', null, null);
