//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:36:20 AM GMT 
//


package com.ail.eft.bacs.output.advices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}OriginatingAccountRecords" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originatingAccountRecords"
})
@XmlRootElement(name = "Advice")
public class Advice {

    @XmlElement(name = "OriginatingAccountRecords")
    protected OriginatingAccountRecords originatingAccountRecords;

    /**
     * Gets the value of the originatingAccountRecords property.
     * 
     * @return
     *     possible object is
     *     {@link OriginatingAccountRecords }
     *     
     */
    public OriginatingAccountRecords getOriginatingAccountRecords() {
        return originatingAccountRecords;
    }

    /**
     * Sets the value of the originatingAccountRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginatingAccountRecords }
     *     
     */
    public void setOriginatingAccountRecords(OriginatingAccountRecords value) {
        this.originatingAccountRecords = value;
    }

}
