//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:36:20 AM GMT 
//


package com.ail.eft.bacs.output.advices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}Header"/>
 *         &lt;element ref="{}AddresseeInformation"/>
 *         &lt;element ref="{}ServiceLicenseInformation" minOccurs="0"/>
 *         &lt;element ref="{}Advice"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ARUDD")
public class ARUDD {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "AddresseeInformation", required = true)
    protected AddresseeInformation addresseeInformation;
    @XmlElement(name = "ServiceLicenseInformation")
    protected ServiceLicenseInformation serviceLicenseInformation;
    @XmlElement(name = "Advice", required = true)
    protected Advice advice;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the addresseeInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AddresseeInformation }
     *     
     */
    public AddresseeInformation getAddresseeInformation() {
        return addresseeInformation;
    }

    /**
     * Sets the value of the addresseeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddresseeInformation }
     *     
     */
    public void setAddresseeInformation(AddresseeInformation value) {
        this.addresseeInformation = value;
    }

    /**
     * Gets the value of the serviceLicenseInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceLicenseInformation }
     *     
     */
    public ServiceLicenseInformation getServiceLicenseInformation() {
        return serviceLicenseInformation;
    }

    /**
     * Sets the value of the serviceLicenseInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceLicenseInformation }
     *     
     */
    public void setServiceLicenseInformation(ServiceLicenseInformation value) {
        this.serviceLicenseInformation = value;
    }

    /**
     * Gets the value of the advice property.
     * 
     * @return
     *     possible object is
     *     {@link Advice }
     *     
     */
    public Advice getAdvice() {
        return advice;
    }

    /**
     * Sets the value of the advice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Advice }
     *     
     */
    public void setAdvice(Advice value) {
        this.advice = value;
    }

}
