//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:36:20 AM GMT 
//


package com.ail.eft.bacs.output.advices;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MessagingHeader"/>
 *         &lt;element ref="{}AddresseeInformation"/>
 *         &lt;element ref="{}MessagingAdvice" maxOccurs="unbounded"/>
 *         &lt;element ref="{}MessagingError"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messagingHeader",
    "addresseeInformation",
    "messagingAdvice",
    "messagingError"
})
@XmlRootElement(name = "MessagingAdvices")
public class MessagingAdvices {

    @XmlElement(name = "MessagingHeader", required = true)
    protected MessagingHeader messagingHeader;
    @XmlElement(name = "AddresseeInformation", required = true)
    protected AddresseeInformation addresseeInformation;
    @XmlElement(name = "MessagingAdvice", required = true)
    protected List<MessagingAdvice> messagingAdvice;
    @XmlElement(name = "MessagingError", required = true)
    protected MessagingError messagingError;

    /**
     * Gets the value of the messagingHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessagingHeader }
     *     
     */
    public MessagingHeader getMessagingHeader() {
        return messagingHeader;
    }

    /**
     * Sets the value of the messagingHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessagingHeader }
     *     
     */
    public void setMessagingHeader(MessagingHeader value) {
        this.messagingHeader = value;
    }

    /**
     * Gets the value of the addresseeInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AddresseeInformation }
     *     
     */
    public AddresseeInformation getAddresseeInformation() {
        return addresseeInformation;
    }

    /**
     * Sets the value of the addresseeInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddresseeInformation }
     *     
     */
    public void setAddresseeInformation(AddresseeInformation value) {
        this.addresseeInformation = value;
    }

    /**
     * Gets the value of the messagingAdvice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messagingAdvice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessagingAdvice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessagingAdvice }
     * 
     * 
     */
    public List<MessagingAdvice> getMessagingAdvice() {
        if (messagingAdvice == null) {
            messagingAdvice = new ArrayList<MessagingAdvice>();
        }
        return this.messagingAdvice;
    }

    /**
     * Gets the value of the messagingError property.
     * 
     * @return
     *     possible object is
     *     {@link MessagingError }
     *     
     */
    public MessagingError getMessagingError() {
        return messagingError;
    }

    /**
     * Sets the value of the messagingError property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessagingError }
     *     
     */
    public void setMessagingError(MessagingError value) {
        this.messagingError = value;
    }

}
