//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:36:20 AM GMT 
//


package com.ail.eft.bacs.output.advices;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="user-number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="record-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="effective-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="reference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="payer-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="payer-account-number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="payer-sort-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="due-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="payment-frequency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amount-of-payment" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="reason-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="payer-new-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="payer-new-account-number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="payer-new-sort-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="new-due-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="new-payment-frequency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amount-of-new-payment" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="last-payment-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="aosn" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="transaction-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orig-sort-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orig-account-number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="orig-ddi-information" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="original-proc-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="originator-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="processing-date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="originator-file-number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="work-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="file-type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accepted-ddi" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="rejected-ddi" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="bureau-number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vol-serial-number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="file-error-code" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="building-society-roll-number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MessagingAdvice")
public class MessagingAdvice {

    @XmlAttribute(name = "user-number")
    protected Integer userNumber;
    @XmlAttribute(name = "record-type")
    protected String recordType;
    @XmlAttribute(name = "effective-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar effectiveDate;
    @XmlAttribute(name = "reference")
    protected String reference;
    @XmlAttribute(name = "payer-name")
    protected String payerName;
    @XmlAttribute(name = "payer-account-number")
    protected Integer payerAccountNumber;
    @XmlAttribute(name = "payer-sort-code")
    protected String payerSortCode;
    @XmlAttribute(name = "due-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlAttribute(name = "payment-frequency")
    protected String paymentFrequency;
    @XmlAttribute(name = "amount-of-payment")
    protected Integer amountOfPayment;
    @XmlAttribute(name = "reason-code")
    protected String reasonCode;
    @XmlAttribute(name = "payer-new-name")
    protected String payerNewName;
    @XmlAttribute(name = "payer-new-account-number")
    protected Integer payerNewAccountNumber;
    @XmlAttribute(name = "payer-new-sort-code")
    protected String payerNewSortCode;
    @XmlAttribute(name = "new-due-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar newDueDate;
    @XmlAttribute(name = "new-payment-frequency")
    protected String newPaymentFrequency;
    @XmlAttribute(name = "amount-of-new-payment")
    protected Integer amountOfNewPayment;
    @XmlAttribute(name = "last-payment-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastPaymentDate;
    @XmlAttribute(name = "aosn")
    protected Integer aosn;
    @XmlAttribute(name = "transaction-code")
    protected String transactionCode;
    @XmlAttribute(name = "orig-sort-code")
    protected String origSortCode;
    @XmlAttribute(name = "orig-account-number")
    protected Integer origAccountNumber;
    @XmlAttribute(name = "orig-ddi-information")
    protected String origDdiInformation;
    @XmlAttribute(name = "original-proc-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar originalProcDate;
    @XmlAttribute(name = "originator-name")
    protected String originatorName;
    @XmlAttribute(name = "processing-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar processingDate;
    @XmlAttribute(name = "originator-file-number")
    protected Integer originatorFileNumber;
    @XmlAttribute(name = "work-code")
    protected String workCode;
    @XmlAttribute(name = "file-type")
    protected String fileType;
    @XmlAttribute(name = "accepted-ddi")
    protected Integer acceptedDdi;
    @XmlAttribute(name = "rejected-ddi")
    protected Integer rejectedDdi;
    @XmlAttribute(name = "bureau-number")
    protected String bureauNumber;
    @XmlAttribute(name = "vol-serial-number")
    protected String volSerialNumber;
    @XmlAttribute(name = "file-error-code")
    protected Integer fileErrorCode;
    @XmlAttribute(name = "building-society-roll-number")
    protected String buildingSocietyRollNumber;

    /**
     * Gets the value of the userNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * Sets the value of the userNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUserNumber(Integer value) {
        this.userNumber = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordType(String value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the payerAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPayerAccountNumber() {
        return payerAccountNumber;
    }

    /**
     * Sets the value of the payerAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPayerAccountNumber(Integer value) {
        this.payerAccountNumber = value;
    }

    /**
     * Gets the value of the payerSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerSortCode() {
        return payerSortCode;
    }

    /**
     * Sets the value of the payerSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerSortCode(String value) {
        this.payerSortCode = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the paymentFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentFrequency() {
        return paymentFrequency;
    }

    /**
     * Sets the value of the paymentFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentFrequency(String value) {
        this.paymentFrequency = value;
    }

    /**
     * Gets the value of the amountOfPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAmountOfPayment() {
        return amountOfPayment;
    }

    /**
     * Sets the value of the amountOfPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAmountOfPayment(Integer value) {
        this.amountOfPayment = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the payerNewName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerNewName() {
        return payerNewName;
    }

    /**
     * Sets the value of the payerNewName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerNewName(String value) {
        this.payerNewName = value;
    }

    /**
     * Gets the value of the payerNewAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPayerNewAccountNumber() {
        return payerNewAccountNumber;
    }

    /**
     * Sets the value of the payerNewAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPayerNewAccountNumber(Integer value) {
        this.payerNewAccountNumber = value;
    }

    /**
     * Gets the value of the payerNewSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerNewSortCode() {
        return payerNewSortCode;
    }

    /**
     * Sets the value of the payerNewSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerNewSortCode(String value) {
        this.payerNewSortCode = value;
    }

    /**
     * Gets the value of the newDueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNewDueDate() {
        return newDueDate;
    }

    /**
     * Sets the value of the newDueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNewDueDate(XMLGregorianCalendar value) {
        this.newDueDate = value;
    }

    /**
     * Gets the value of the newPaymentFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewPaymentFrequency() {
        return newPaymentFrequency;
    }

    /**
     * Sets the value of the newPaymentFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewPaymentFrequency(String value) {
        this.newPaymentFrequency = value;
    }

    /**
     * Gets the value of the amountOfNewPayment property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAmountOfNewPayment() {
        return amountOfNewPayment;
    }

    /**
     * Sets the value of the amountOfNewPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAmountOfNewPayment(Integer value) {
        this.amountOfNewPayment = value;
    }

    /**
     * Gets the value of the lastPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastPaymentDate() {
        return lastPaymentDate;
    }

    /**
     * Sets the value of the lastPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastPaymentDate(XMLGregorianCalendar value) {
        this.lastPaymentDate = value;
    }

    /**
     * Gets the value of the aosn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAosn() {
        return aosn;
    }

    /**
     * Sets the value of the aosn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAosn(Integer value) {
        this.aosn = value;
    }

    /**
     * Gets the value of the transactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionCode() {
        return transactionCode;
    }

    /**
     * Sets the value of the transactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCode(String value) {
        this.transactionCode = value;
    }

    /**
     * Gets the value of the origSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigSortCode() {
        return origSortCode;
    }

    /**
     * Sets the value of the origSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigSortCode(String value) {
        this.origSortCode = value;
    }

    /**
     * Gets the value of the origAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrigAccountNumber() {
        return origAccountNumber;
    }

    /**
     * Sets the value of the origAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrigAccountNumber(Integer value) {
        this.origAccountNumber = value;
    }

    /**
     * Gets the value of the origDdiInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigDdiInformation() {
        return origDdiInformation;
    }

    /**
     * Sets the value of the origDdiInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigDdiInformation(String value) {
        this.origDdiInformation = value;
    }

    /**
     * Gets the value of the originalProcDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalProcDate() {
        return originalProcDate;
    }

    /**
     * Sets the value of the originalProcDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalProcDate(XMLGregorianCalendar value) {
        this.originalProcDate = value;
    }

    /**
     * Gets the value of the originatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatorName() {
        return originatorName;
    }

    /**
     * Sets the value of the originatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatorName(String value) {
        this.originatorName = value;
    }

    /**
     * Gets the value of the processingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProcessingDate() {
        return processingDate;
    }

    /**
     * Sets the value of the processingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProcessingDate(XMLGregorianCalendar value) {
        this.processingDate = value;
    }

    /**
     * Gets the value of the originatorFileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOriginatorFileNumber() {
        return originatorFileNumber;
    }

    /**
     * Sets the value of the originatorFileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOriginatorFileNumber(Integer value) {
        this.originatorFileNumber = value;
    }

    /**
     * Gets the value of the workCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkCode() {
        return workCode;
    }

    /**
     * Sets the value of the workCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkCode(String value) {
        this.workCode = value;
    }

    /**
     * Gets the value of the fileType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * Sets the value of the fileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileType(String value) {
        this.fileType = value;
    }

    /**
     * Gets the value of the acceptedDdi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAcceptedDdi() {
        return acceptedDdi;
    }

    /**
     * Sets the value of the acceptedDdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAcceptedDdi(Integer value) {
        this.acceptedDdi = value;
    }

    /**
     * Gets the value of the rejectedDdi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRejectedDdi() {
        return rejectedDdi;
    }

    /**
     * Sets the value of the rejectedDdi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRejectedDdi(Integer value) {
        this.rejectedDdi = value;
    }

    /**
     * Gets the value of the bureauNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauNumber() {
        return bureauNumber;
    }

    /**
     * Sets the value of the bureauNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauNumber(String value) {
        this.bureauNumber = value;
    }

    /**
     * Gets the value of the volSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolSerialNumber() {
        return volSerialNumber;
    }

    /**
     * Sets the value of the volSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolSerialNumber(String value) {
        this.volSerialNumber = value;
    }

    /**
     * Gets the value of the fileErrorCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFileErrorCode() {
        return fileErrorCode;
    }

    /**
     * Sets the value of the fileErrorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFileErrorCode(Integer value) {
        this.fileErrorCode = value;
    }

    /**
     * Gets the value of the buildingSocietyRollNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingSocietyRollNumber() {
        return buildingSocietyRollNumber;
    }

    /**
     * Sets the value of the buildingSocietyRollNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingSocietyRollNumber(String value) {
        this.buildingSocietyRollNumber = value;
    }

}
