//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 10:36:20 AM GMT 
//


package com.ail.eft.bacs.output.advices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ail.eft.bacs.output.advices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReturnedDebitItem_QNAME = new QName("", "ReturnedDebitItem");
    private final static QName _Address3_QNAME = new QName("", "address3");
    private final static QName _Address2_QNAME = new QName("", "address2");
    private final static QName _Address1_QNAME = new QName("", "address1");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Address5_QNAME = new QName("", "address5");
    private final static QName _Address4_QNAME = new QName("", "address4");
    private final static QName _ReturnedCreditItem_QNAME = new QName("", "ReturnedCreditItem");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ail.eft.bacs.output.advices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BACSDocument }
     * 
     */
    public BACSDocument createBACSDocument() {
        return new BACSDocument();
    }

    /**
     * Create an instance of {@link ReturnedItemType }
     * 
     */
    public ReturnedItemType createReturnedItemType() {
        return new ReturnedItemType();
    }

    /**
     * Create an instance of {@link Totals }
     * 
     */
    public Totals createTotals() {
        return new Totals();
    }

    /**
     * Create an instance of {@link MessagingAdvice }
     * 
     */
    public MessagingAdvice createMessagingAdvice() {
        return new MessagingAdvice();
    }

    /**
     * Create an instance of {@link ARUCS }
     * 
     */
    public ARUCS createARUCS() {
        return new ARUCS();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link AddresseeInformation }
     * 
     */
    public AddresseeInformation createAddresseeInformation() {
        return new AddresseeInformation();
    }

    /**
     * Create an instance of {@link ServiceLicenseInformation }
     * 
     */
    public ServiceLicenseInformation createServiceLicenseInformation() {
        return new ServiceLicenseInformation();
    }

    /**
     * Create an instance of {@link Advice }
     * 
     */
    public Advice createAdvice() {
        return new Advice();
    }

    /**
     * Create an instance of {@link OriginatingAccountRecords }
     * 
     */
    public OriginatingAccountRecords createOriginatingAccountRecords() {
        return new OriginatingAccountRecords();
    }

    /**
     * Create an instance of {@link OriginatingAccountRecord }
     * 
     */
    public OriginatingAccountRecord createOriginatingAccountRecord() {
        return new OriginatingAccountRecord();
    }

    /**
     * Create an instance of {@link ServiceLevelLicenseInformation }
     * 
     */
    public ServiceLevelLicenseInformation createServiceLevelLicenseInformation() {
        return new ServiceLevelLicenseInformation();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link BACSDocument.Data }
     * 
     */
    public BACSDocument.Data createBACSDocumentData() {
        return new BACSDocument.Data();
    }

    /**
     * Create an instance of {@link MessagingHeader }
     * 
     */
    public MessagingHeader createMessagingHeader() {
        return new MessagingHeader();
    }

    /**
     * Create an instance of {@link MessagingAdvices }
     * 
     */
    public MessagingAdvices createMessagingAdvices() {
        return new MessagingAdvices();
    }

    /**
     * Create an instance of {@link MessagingError }
     * 
     */
    public MessagingError createMessagingError() {
        return new MessagingError();
    }

    /**
     * Create an instance of {@link ARUDD }
     * 
     */
    public ARUDD createARUDD() {
        return new ARUDD();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnedItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReturnedDebitItem")
    public JAXBElement<ReturnedItemType> createReturnedDebitItem(ReturnedItemType value) {
        return new JAXBElement<ReturnedItemType>(_ReturnedDebitItem_QNAME, ReturnedItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address3")
    public JAXBElement<String> createAddress3(String value) {
        return new JAXBElement<String>(_Address3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address1")
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address5")
    public JAXBElement<String> createAddress5(String value) {
        return new JAXBElement<String>(_Address5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address4")
    public JAXBElement<String> createAddress4(String value) {
        return new JAXBElement<String>(_Address4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReturnedItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReturnedCreditItem")
    public JAXBElement<ReturnedItemType> createReturnedCreditItem(ReturnedItemType value) {
        return new JAXBElement<ReturnedItemType>(_ReturnedCreditItem_QNAME, ReturnedItemType.class, null, value);
    }

}
